# Generated by Django 5.2.14 on 2026-05-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
