# Generated by Django 5.2.14 on 2026-05-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_appuser_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
