# Generated by Django 5.2.14 on 2026-05-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_appuser_is_customer'),
    ]

    operations = [
    ]
